version: 0.2

env:
  variables:
    LC_ALL: en_US.utf-8
    LANG: en_US.utf-8

phases:
  pre_build:
    commands:
      - echo '{ "allow_root":true }' >> /root/.bowerrc
  
  build:
    commands:
      - echo Build started on `date`
      
      # Perform build.
      - boa-nimbus build --no-use-docker
      
      # Move output directory.
      - mv build/artifacts /tmp/
      - rm -rf *
      - rm -rf .git
      - rm -rf .gitignore
      - mv /tmp/artifacts/* .
  
  post_build:
    commands:
      - echo Build completed on `date`

artifacts:
  files:
    - '**/*'
  